name: User-Register CI with Maven (JDK 21)

on:
  push:
    branches: [ "main", "user-register", "feature/**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for SonarQube analysis

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Analyze
      env:
        SONAR_TOKEN: eb5f15aa821183f571ecc33890f00296aad90583
        # If using SonarCloud, SONAR_HOST_URL is optional as it defaults to sonarcloud.io
        SONAR_HOST_URL: https://sonarcloud.io/
      run: >
        mvn -B verify sonar:sonar 
        -Dspring.profiles.active=test 
        -Dsonar.projectKey=vishnurajv1258_user-register
        -Dsonar.projectName='user-register'

    - name: Upload Build Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: microservice-executable
        path: target/*.jar
        retention-days: 2
